### ISSUE TITLE
Subtitle tracks are shown twice

### ISSUE THREAD

**Issue by PionerJn** [codeit-ninja/SRT-Support-for-HTML5-videos#14]
Hi,

Thanks for this little js, it's very useful.

Languages appear twice in the menu for me, but only the second ones are working:

![image](https://github.com/codeit-ninja/SRT-Support-for-HTML5-videos/assets/69699451/7378d8fd-4744-4034-b67d-7fc69c0361e4)

Reproduction of the issue can be found [here](https://codepen.io/pionerjn/pen/mdogXZV)

Thanks,

**Comment by codeit-ninja** [comment]
Bug will be fixed in the next version, thanks for reporting
