### ISSUE TITLE
Include the original (prettyfied) version of dist/main.iife.js

### ISSUE THREAD

**Issue by lwcorp** [codeit-ninja/SRT-Support-for-HTML5-videos#5]
`dist/main.iife.js` is a minimized file, which should be included in releases, but pure source codes should also include the original version.

Can you please include it? You can call it something like `dist/main.iife_original.js`.

**Comment by codeit-ninja** [comment]
The pure source code is included, its the `main.js` file. The `import`'s are comming from the '/src' folder.

**Comment by lwcorp** [comment]
I meant for [the CDN version](https://github.com/codeit-ninja/SRT-Support-for-HTML5-videos#installation) which is a standalone file that doesn't rely on anything else but itself.

Since it's a completely standalone file, could you please include its original prettified version in the source code? While it's possible to use converters to prettify it artifically, all function names are lost, etc. and obviously so do 100% of the comments that probably exist in the original.

**Comment by codeit-ninja** [comment]
Project uses *vitejs* and *rollup*, I will add a new build command which takes care of that. Feature will be added in next commit.

**Comment by lwcorp** [comment]
Do you mean this part will also have a parallel ` dist/main.iife_original.js` file to serve as a transparent open source code?
![image](https://user-images.githubusercontent.com/1773306/179299552-edfad52e-58f9-406b-b173-821e347cc30a.png)

**Comment by lwcorp** [comment]
Why was this marked as completed if there was never a next commit? This very essential script - the only file for CDN usage - is still minified. I think completion should be marked only after code is added, not before.

**Comment by codeit-ninja** [comment]
Because I added the requested unminified file in commit 118c73c46bed8547eea1eb5b2f6bfc52fa4fb4b3. You can see that I closed it with a commit which resolved the issue.

**Comment by lwcorp** [comment]
So just pointing out the original source is therefore `/dist/source.es.js`. Thanks for your commit!

**Comment by lwcorp** [comment]
Can you keep it up to date? It's currently months behind the minimized file:
![image](https://user-images.githubusercontent.com/1773306/213873453-fba4ada6-4563-4a05-9755-2df2ad07bf02.png)

**Comment by codeit-ninja** [comment]
Sorry, I removed this from the build process.

This is not how you are supposed to use packages.
I think you miss the knowledge of using packages,

Maybe start learning from here how to use packages
https://docs.npmjs.com/using-npm-packages-in-your-projects

If you want to include the source and use the code, then copy over the code from the `src` directory. Or clone this repo and build it from source.

**Comment by lwcorp** [comment]
Then you might want to delete https://github.com/codeit-ninja/SRT-Support-for-HTML5-videos/blob/master/dist/source.es.js (which is outdated) if it was a manual process to create it anyway, and you don't want to do it each time.
